name: askaris
description: Transportation App
publish_to: 'none'
version: 1.0.5+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.0

  # Firebase Stack

  firebase_core: ^0.5.0+1
  # Database
  cloud_firestore: ^0.14.1+3
  # Storage
  firebase_storage: ^4.0.0
  # Authentication
  firebase_auth: ^0.18.1+2
  google_sign_in:
  # Messaging
  firebase_messaging: ^7.0.0
  # Analytics
  firebase_analytics: ^6.0.0
  # Crashlytics
  firebase_crashlytics: ^0.2.0
  # Performance
  firebase_performance: ^0.4.0
  
  # TDLib Dependencies

  tdlib: ^1.3.0
  # URL Launcher
  url_launcher: ^5.4.5
  # Native Share Sheet
  share: ^0.6.4+1
  # Device Informations for Telegram Client
  device_info: ^0.4.2+4
  # Image Cropper and Picker
  image_picker: ^0.6.6+2
  image_cropper: ^1.2.3
  # Version and Package Name Validation Checker
  package_info: ^0.4.1
  provider: ^4.3.1
  path_provider: ^1.6.10
  permission_handler: ^5.0.1
  country_pickers: ^1.2.1
  get_it: ^1.0.3

  # Navigation Stack
  modal_bottom_sheet: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    # Inter
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.otf
        - asset: fonts/Inter-BlackItalic.otf
        - asset: fonts/Inter-Bold.otf
        - asset: fonts/Inter-BoldItalic.otf
        - asset: fonts/Inter-Semibold.otf
        - asset: fonts/Inter-SemiboldItalic.otf
        - asset: fonts/Inter-ExtraBold.otf
        - asset: fonts/Inter-ExtraBoldItalic.otf
        - asset: fonts/Inter-Light.otf
        - asset: fonts/Inter-LightItalic.otf
        - asset: fonts/Inter-ExtraLight.otf
        - asset: fonts/Inter-ExtraLightItalic.otf
        - asset: fonts/Inter-Medium.otf
        - asset: fonts/Inter-MediumItalic.otf
        - asset: fonts/Inter-Regular.otf
        - asset: fonts/Inter-Italic.otf
        - asset: fonts/Inter-Thin.otf
        - asset: fonts/Inter-ThinItalic.otf