name: projekt_askaris
description: Transportation App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.4+2
  firebase_analytics: ^5.0.15
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.3
  cloud_firestore: ^0.13.4+1
  url_launcher: ^5.4.5
  flutter_vector_icons: ^0.2.1
  share: ^0.6.4+1
  device_info: ^0.4.2+4
  image_picker: ^0.6.6+2
  image_cropper: ^1.2.3
  package_info: ^0.4.1
  modal_bottom_sheet: 0.2.0+1
  webview_flutter: 0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.otf
        - asset: fonts/Inter-BlackItalic.otf
        - asset: fonts/Inter-Bold.otf
        - asset: fonts/Inter-BoldItalic.otf
        - asset: fonts/Inter-Semibold.otf
        - asset: fonts/Inter-SemiboldItalic.otf
        - asset: fonts/Inter-ExtraBold.otf
        - asset: fonts/Inter-ExtraBoldItalic.otf
        - asset: fonts/Inter-Light.otf
        - asset: fonts/Inter-LightItalic.otf
        - asset: fonts/Inter-ExtraLight.otf
        - asset: fonts/Inter-ExtraLightItalic.otf
        - asset: fonts/Inter-Medium.otf
        - asset: fonts/Inter-MediumItalic.otf
        - asset: fonts/Inter-Regular.otf
        - asset: fonts/Inter-Italic.otf
        - asset: fonts/Inter-Thin.otf
        - asset: fonts/Inter-ThinItalic.otf